
# Start interactive session

```
srun --qos=general --mem=16GB --pty bash
```

# Download miniforge installer
```
wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
```

# Install miniforge
```bash
bash Miniforge3.sh
```

1. Agree to license terms (yes)
2. Choose installation path (default is fine)
3. Choose whether to initialize mamba (select "yes")

```bash
source ~/.bashrc
```

# Create environment
Note the use of `mamba` instead of `conda`. Mamba is a faster drop-in replacement for conda. It is recommended to use mamba for creating environments and installing packages.
```
conda create -n single-cell python=3.11
```
1. Confirm changes (y)

# Activate environment
```
conda activate single-cell
```

# Install dependencies
## single-cell environment
Installing dependencies into your `single-cell` environment.

### Dependencies for 05_filter_ambient
```
conda install -c conda-forge -c bioconda jupyter scanpy rpy2 anndata2ri scipy \
python-igraph r-soupx 
```

### Addition dependencies for 06_doublet_detection & 07_qc_filtering
```
conda install -c conda-forge -c bioconda bioconductor-scdblfinder upsetplot 
```

### Additional dependencies for 08_preprocessing & 09_annotation, 10_pseudotime
```
conda install -c conda-forge -c bioconda harmonypy scikit-misc palantir 
```

### Additional dependencies for 12_diff_exp, use single-cell environment
```
conda install -c conda-forge -c bioconda decoupler-py bioconductor-deseq2 adjusttext
```

### Additional dependencies for 13_interop, use single-cell environment
```
conda install -c conda-forge -c bioconda r-seurat bioconductor-anndatar \
bioconductor-rhdf5 bioconductor-scater
```

## Create environment for 11_composition
Dependencies for the 11_composition script conflict with the single-cell environment. 
Therefore, we need to create a new environment for this script.
```
conda create -n sc-composition -c conda-forge -c bioconda python=3.11 jupyter scanpy \
pertpy pandas matplotlib seaborn
```

## One line to create single-cell environment
If you are not in a hurry, you can create the single-cell environment with all dependencies in one line. This will take a while to resolve and install all dependencies.
```
conda create -n single-cell -c conda-forge -c bioconda jupyter scanpy rpy2 anndata2ri scipy \
python-igraph r-soupx bioconductor-scdblfinder upsetplot harmonypy scikit-misc \
palantir decoupler-py bioconductor-deseq2 adjusttext r-seurat bioconductor-anndatar \
bioconductor-rhdf5 bioconductor-scater
```